### PR TITLE
Configure hostname, and hots file using the first domain configured in yunohost

### PR DESCRIPTION
**Pull request by sbadia**
Get the first domain configured in yunhost, and configure hostname, and hosts files (fix hostname, fqdn issues).

### CODE REVIEW

**Comment by sbadia** [comment]
@Psycojoker @jvaubourg ready for review!

**Comment by Psycojoker** [comment]
Shouldn't we check that a valid hostname isn't already configured? Something like "there a `.` in this string" should be enough I think.

**Comment by jvaubourg** [comment]
It's okay for me, thx.

(but I think that this should not be in DoctorCube because it's not a Cube-related issue, but something to fix directly on the YunoHost side - cf. https://dev.yunohost.org/issues/341 ).

**Comment by sbadia** [comment]
@jvaubourg I agree, but it's not really a blocker here, we can push this fix on the two side, no?

**Comment by jvaubourg** [comment]
Yep, you're right, this can be in doctorcube, waiting for a fix in yunohost.

**Comment by Psycojoker** [comment]
Hm, we should handle app upgrade script before update the labriqueinternet.json

**Comment by Psycojoker** [comment]
I can take a look at that if you want

**Comment by jvaubourg** [comment]
@Psycojoker Is really there a concept of upgrading with this app? If we do an upgrade script, all content inside the install script, added from now, will be duplicated in the upgrade script.

I think we should add conditions everywhere in the install script (like sebian did it here), and just execute it in the upgrade script.

**Comment by Psycojoker** [comment]
@jvaubourg I find it very counter intuitive for an user to have everything rerun all the time, this can lead to unexpected behavior if he has made his own modifications.

Regarding code duplication we can adopt the pattern I've adopted for neutrinet_ynh, this end up being pretty efficient: https://github.com/Neutrinet/neutrinet_ynh/blob/master/scripts/upgrade

**Pull request merged**
